#!/bin/bash

dep ensure -v
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o spot-instance-webhook
docker build --no-cache -t theryanbaker/spot-instance-webhook:v1 .
rm -rf spot-instance-webhook

docker push theryanbaker/spot-instance-webhook:v1