[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.14"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.14"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.14"

[prune]
  go-tests = true
  unused-packages = true

# Fix: vendor/k8s.io/kubernetes/pkg/util/parsers/parsers.go:36:16: undefined: reference.ParseNormalizedNamed
[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[override]]
  name = "github.com/json-iterator/go"
  #revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"
  version = "v1.1.9"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.14"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.14"

#[[constraint]]
#  name = "k8s.io/client-go"
#  version = "7.0.0"
