apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spot-instance-webhook
  labels:
    app: spot-instance-webhook
rules:
- apiGroups:
  - banzaicloud.com  # TODO:  What is an API Group rule?
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'