apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: spot-instance-webhook
  labels:
    app: spot-instance-webhook
webhooks:
  - name:  spot-instance.handler.c2fo.com
    clientConfig:
      service:
        name: spot-instance-webhook
        namespace: default
        path: "/mutate"
      caBundle: {{ .Values.CABundle }}
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1", "v1beta1"]
        resources: ["deployments"]
    namespaceSelector:
      matchLabels:
        spot-deploy: enabled

