apiVersion: v1
kind: Service
metadata:
  name: spot-instance-webhook
  labels:
    app: spot-instance-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: spot-instance-webhook
