apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: spot-instance-webhook
  labels:
    app: spot-instance-webhook
webhooks:
  - name: spot-instance-webhook
    clientConfig:
      service:
        name: spot-instance-webhook
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1", "v1beta1"]
        resources: ["deployments"]
    namespaceSelector:
      matchLabels:
        spot-deploy: enabled

