apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: label-namespace-webhook
  labels:
    app: label-namespace-webhook
webhooks:
  - name:  spot-instance.handler.c2fo.com
    clientConfig:
      service:
        name: spot-instance-webhook
        namespace: default
        path: "/mutate"
      caBundle: {{ .Values.CABundle }}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["namespaces", ""]
        apiVersions: ["v1", "v1beta1"]
        resources: ["namespaces"]

