kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spot-instance-webhook
  labels:
    app: spot-instance-webhook
subjects:
- kind: ServiceAccount
  name: spot-instance-webhook
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spot-instance-webhook