on: [push]

jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest
    name: Builds the Docker Image for Spot Instance Handler
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker Image
      id: build
      #uses: actions/spot-instance-webhook@v1
      uses: ./
      # with:
      #   who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time was ${{ steps.hello.outputs.time }}"