on: [push]

jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest
    name: Builds the Docker Image for Spot Instance Handler
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag theryanbaker/spot-instance-webhook:traptest2
    - name: Push the Image to Docker
      run: docker push theryanbaker/spot-instance-webhook:traptest2